Controllers/SiteUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc4App.Models;

namespace Mvc4App.Controllers
{
    public class SiteUserController : Controller
    {
        private dukeofaustinEntities db = new dukeofaustinEntities();

        //
        // GET: /SiteUser/

        public ActionResult Index()
        {
            return View(db.SiteAppUsers.ToList());
        }

        //
        // GET: /SiteUser/Details/5

        public ActionResult Details(int id = 0)
        {
            SiteAppUser siteappuser = db.SiteAppUsers.Find(id);
            if (siteappuser == null)
            {
                return HttpNotFound();
            }
            return View(siteappuser);
        }

        //
        // GET: /SiteUser/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // GET: /SiteUser/Edit/5

        public ActionResult Show(int id = 0)
        {
            SiteAppUser siteappuser = db.SiteAppUsers.Find(id);
            return PartialView(siteappuser);
        }

        //
        // POST: /SiteUser/Edit/5

        [HttpPost]
        public ActionResult Show(SiteAppUser siteappuser)
        {
            if (ModelState.IsValid)
            {
                siteappuser.Audit = GetAuditString();
                db.Entry(siteappuser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView(siteappuser);
        }
        //
        // POST: /SiteUser/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SiteAppUser siteappuser)
        {
            if (ModelState.IsValid)
            {
                siteappuser.Audit = GetAuditString("Ins-");
                db.SiteAppUsers.Add(siteappuser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(siteappuser);
        }

        //
        // GET: /SiteUser/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SiteAppUser siteappuser = db.SiteAppUsers.Find(id);
            if (siteappuser == null)
            {
                return HttpNotFound();
            }
            return View(siteappuser);
        }

        //
        // POST: /SiteUser/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SiteAppUser siteappuser)
        {
            if (ModelState.IsValid)
            {
                siteappuser.Audit = GetAuditString();
                db.Entry(siteappuser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(siteappuser);
        }
  
        //
        // GET: /SiteUser/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SiteAppUser siteappuser = db.SiteAppUsers.Find(id);
            if (siteappuser == null)
            {
                return HttpNotFound();
            }
            return View(siteappuser);
        }

        //
        // POST: /SiteUser/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SiteAppUser siteappuser = db.SiteAppUsers.Find(id);
            db.SiteAppUsers.Remove(siteappuser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private string GetAuditString(string prefix = "Upd-")
        {
            DateTime now = DateTime.Now;
            var rtn = prefix + String.Format("{0:d/M/yyyy HH:mm:ss}", now);
            return rtn;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Prototype</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes")
   <link href="/Content/themes/jquery-ui-1.11.1.custom/jquery-ui.structure.min.css" rel="stylesheet"/>
   <link href="/Content/themes/jquery-ui-1.11.1.custom/jquery-ui.theme.min.css"  rel="stylesheet"/>
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")

        @Scripts.Render("~/bundles/jqueryui")      
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jquerycus")
    <script src="@Url.Content("~/Scripts/Custom.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            $("#tabs").tabmenu();
        });
    </script>

  </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink(" ", "Index", "Home", null,  new { style = "background: url('" + Url.Content("~/images/prototypetitle.png") + "') no-repeat center right; display:block; height:84px; width:350px;" })</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                   
                    <nav>
                         <div id="tabs">
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Users", "Index", "SiteUser")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                             </div>
                    </nav> 

                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                 <p>&copy; @DateTime.Now.Year - DukeOfAustin</p>
            </div>
        </footer>



        @if (IsSectionDefined("Scripts"))
        {
           RenderSection("Scripts", false);
        }
      
    </body>
</html>